version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:

      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

